"""add coupons, inventory transactions, order status history

Revision ID: 1a703009642e
Revises: 89bcc54cb973
Create Date: 2026-07-15 04:10:25.299863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '1a703009642e'
down_revision: Union[str, None] = '89bcc54cb973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # order_status already exists (from the initial migration); add the new
    # RETURNED value to it rather than letting autogenerate try to CREATE TYPE
    # again for order_status_history below.
    op.execute("ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'RETURNED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('discount_type', sa.Enum('FIXED', 'PERCENTAGE', name='coupon_discount_type'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('free_shipping', sa.Boolean(), nullable=False),
    sa.Column('min_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('per_user_limit', sa.Integer(), nullable=True),
    sa.Column('applicable_categories', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('applicable_products', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('coupon_redemptions',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('amount_discounted', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status_history',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column(
        'status',
        postgresql.ENUM(
            'PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED',
            name='order_status', create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_transactions',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('change_quantity', sa.Integer(), nullable=False),
    sa.Column('resulting_quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('ORDER_PLACED', 'ORDER_CANCELLED', 'RETURN', 'ADMIN_ADJUSTMENT', name='inventory_change_reason'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('carts', sa.Column('coupon_code', sa.String(length=40), nullable=True))
    op.add_column(
        'orders',
        sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'),
    )
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=40), nullable=True))
    op.add_column('orders', sa.Column('customer_notes', sa.String(length=1000), nullable=True))
    # NOTE: autogenerate wants to drop+recreate the occasion/season/style_tags GIN
    # indexes here - that's a false positive (ARRAY columns aren't declared with
    # postgresql_using at the ORM level, so autogenerate always sees them as
    # "different"). Deliberately not touching those indexes in this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_notes')
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('carts', 'coupon_code')
    op.drop_table('inventory_transactions')
    op.drop_table('order_status_history')
    op.drop_table('coupon_redemptions')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
