"""extend style profile with full preference fields

Revision ID: 28995c8e7dc4
Revises: 62b95f8bdcbd
Create Date: 2026-07-14 19:23:43.452330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '28995c8e7dc4'
down_revision: Union[str, None] = '62b95f8bdcbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style_profiles', sa.Column('gender_presentation', sa.String(length=20), nullable=True))
    op.add_column(
        'style_profiles',
        sa.Column('disliked_colors', sa.ARRAY(sa.String()), nullable=False, server_default='{}'),
    )
    op.add_column(
        'style_profiles',
        sa.Column('favorite_occasions', sa.ARRAY(sa.String()), nullable=False, server_default='{}'),
    )
    op.add_column(
        'style_profiles',
        sa.Column('preferred_brands', sa.ARRAY(sa.String()), nullable=False, server_default='{}'),
    )
    op.add_column('style_profiles', sa.Column('budget_min', sa.Integer(), nullable=True))
    op.add_column('style_profiles', sa.Column('budget_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('style_profiles', 'budget_max')
    op.drop_column('style_profiles', 'budget_min')
    op.drop_column('style_profiles', 'preferred_brands')
    op.drop_column('style_profiles', 'favorite_occasions')
    op.drop_column('style_profiles', 'disliked_colors')
    op.drop_column('style_profiles', 'gender_presentation')
    # ### end Alembic commands ###
